import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsIn,
  IsBoolean,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  MaxLength,
  Min,
} from 'class-validator';

export class ScanCouponIssueDto {
  @ApiProperty({
    example:
      'https://nightlife.vn/partner/scan?token=opaque-token.signature',
    description:
      'Opaque signed QR token or deep link generated by the backend.',
  })
  @IsString()
  @MaxLength(1024)
  payload!: string;

  @ApiPropertyOptional({ example: false })
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  offline?: boolean;
}

export class AdminCouponIssueQueryDto {
  @ApiPropertyOptional({ example: '550e8400-e29b-41d4-a716-446655440000' })
  @IsOptional()
  @IsUUID()
  storeId?: string;

  @ApiPropertyOptional({ example: '550e8400-e29b-41d4-a716-446655440000' })
  @IsOptional()
  @IsUUID()
  couponId?: string;

  @ApiPropertyOptional({ example: 'ISSUED' })
  @IsOptional()
  @IsString()
  @IsIn(['ISSUED', 'USED', 'EXPIRED', 'REVOKED'])
  status?: string;

  @ApiPropertyOptional({ example: 50 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  limit?: number;
}
