import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform, Type } from 'class-transformer';
import {
  ArrayMaxSize,
  IsArray,
  IsBoolean,
  IsEmail,
  IsISO8601,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  Matches,
  Max,
  MaxLength,
  Min,
  MinLength,
  ValidateNested,
} from 'class-validator';

const trimString = ({ value }: { value: unknown }) =>
  typeof value === 'string' ? value.trim() : value;

const trimOptionalString = ({ value }: { value: unknown }) => {
  if (typeof value !== 'string') return value;
  return value.trim() || undefined;
};

export class TourBookingCastSelectionDto {
  @IsUUID()
  storeId!: string;

  @IsArray()
  @ArrayMaxSize(10)
  @IsUUID(undefined, { each: true })
  castIds!: string[];
}

export class CreateTourBookingDto {
  @ApiProperty({ example: 'Nguyen Van A' })
  @Transform(trimString)
  @IsNotEmpty()
  @IsString()
  @MinLength(2)
  @MaxLength(80)
  @Matches(/^[\p{L}\p{M}\s]+$/u, {
    message: 'displayName must contain letters and spaces only',
  })
  displayName!: string;

  @ApiProperty({ example: 'guest@example.com' })
  @Transform(({ value }) =>
    typeof value === 'string' ? value.trim().toLowerCase() : value,
  )
  @IsEmail()
  @MaxLength(254)
  email!: string;

  @ApiPropertyOptional({ example: '+84901234567' })
  @Transform(trimOptionalString)
  @IsOptional()
  @IsString()
  @MaxLength(20)
  @Matches(/^[0-9+\-\s().]{8,20}$/)
  phone?: string;

  @ApiProperty({ example: '2026-07-17T13:00:00.000Z' })
  @IsISO8601()
  scheduledAt!: string;

  @ApiProperty({ minimum: 1, maximum: 50, example: 4 })
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(50)
  partySize!: number;

  @ApiPropertyOptional()
  @Transform(trimOptionalString)
  @IsOptional()
  @IsString()
  @MaxLength(300)
  note?: string;

  @ApiPropertyOptional({ type: [TourBookingCastSelectionDto] })
  @IsOptional()
  @IsArray()
  @ArrayMaxSize(20)
  @ValidateNested({ each: true })
  @Type(() => TourBookingCastSelectionDto)
  castSelections?: TourBookingCastSelectionDto[];
}

export class ScanTourBookingQrDto {
  @ApiProperty({
    description:
      'Signed tour QR payload or deep link generated by the backend.',
  })
  @IsString()
  @MaxLength(2048)
  payload!: string;

  @ApiProperty({ description: 'Store currently selected in the partner app.' })
  @IsUUID()
  activeStoreId!: string;

  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  offline?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsISO8601()
  clientScannedAt?: string;
}

export class ConfirmTourBookingCheckInDto {
  @ApiProperty({
    description:
      'Short-lived signed confirmation token returned by QR preview.',
  })
  @IsString()
  @MaxLength(2048)
  scanSessionToken!: string;

  @ApiPropertyOptional()
  @Transform(trimOptionalString)
  @IsOptional()
  @IsUUID()
  idempotencyKey?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsISO8601()
  clientScannedAt?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Boolean)
  @IsBoolean()
  offline?: boolean;
}
